# Site settings
baseURL = "https://nilezhou.github.io"
languageCode = "en-gb"
title = "ATFutures"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Active Transport Futures"
  description = "global scale open source software for planning urban futures for active transport"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "ATFutures"
    subtitle = "Active Transport Futures"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "About Us"
      url = "about-us"

    [[params.navigation.links]]
      name = "Events"
      url = "events"

    [[params.navigation.links]]
      name = "Blog"
      url = "blogs"

    #[[params.navigation.links]]
    #  name = "Generic Blog"
    #  url = "blogs/ipsum"

    #[[params.navigation.links]]
    #  name = "Elements"
    #  url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "about-us"

    # Button Style 2
    #[[params.navigation.button2]]
    #  name = "Log In"
    #  url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'Banner.jpg' in
    # the 'static/img' folder.
    title = "Active Transport Futures"
    subtitle = "Globally scalable, open-source tools using open data to plan urban futures in which active transport plays an increasingly prominent role. Our tools are used by the World Health Organization, and enable highly detailed, city-wide estimation of current transport patterns; estimation of response to planned modifications to tranport infrastructure; and conversion of responses into aggregate health and economic terms."
    buttonText = "More Information"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "The ATFutures Toolkit"
      subtitle = "Our modular toolkit for planning and monitoring Active Transport Futures"
      image = "pic01.jpg"
      url = "about-us/atft"

    [[params.tiles.showcase]]
      title = "World Health Organization"
      subtitle = "Our prototype tool for the World Health Organziation"
      image = "pic03.jpg"
      url = "about-us/who1"

    [[params.tiles.showcase]]
      title = "The Propensity to Cycle Tool (PCT)"
      subtitle = "The United Kingdom PCT and the Cycling Infrastructure Prioritization Toolkit"
      image = "pic02.jpg"
      url = "about-us/pct"

    [[params.tiles.showcase]]
      title = "ATFutures People"
      subtitle = "Who Are We?"
      image = "robin-mark.jpg"
      url = "about-us/people"

    [[params.tiles.showcase]]
      title = "Software"
      subtitle = "Our Software"
      image = "thessaloniki.jpg"
      url = "about-us/software"

    [[params.tiles.showcase]]
      title = "Data"
      subtitle = "The Data We Use"
      image = "pic06.jpg"
      url = "about-us/data"

    # You can make more showcases by copy and pasting the code above

  [params.about-us]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Context"
    subtitle = """Why Active Transport Futures?
    Transport planning software was originally designed to plan for motorised transport.
    The latest scientific evidence shows that this type of planning is no longer sustainable.
    From a health perspective over-reliance on motor vehicles is damaging, an issue that
    planning for active transport can address by making physical activity part of everyday life.
    Active transport also helps cities address related issues of road traffic deaths,
    greenhouse gas emissions targets and air pollution."""
    buttonText = "Get Started"
    url = "about-us"
    
  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "mark.padgham@email.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "R.Lovelace@leeds.ac.uk"

    [[params.contact.email]]
    #title = "Email"
    email = "mark.padgham@email.com"

    #[[params.contact.phone]]
    #title = "Phone"
    #phone = "(000) 000-0000 x1234"

    #[[params.contact.address]]
    #title = "Address"
    #street = "Street"
    #city = "City, ST 00000"
    #country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "ATFutures"

    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/RobinLovelace"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/mpadge"
      label = "Twitter"

    #[[params.footer.social]]
    #  icon = "fa-facebook"
    #  url= "https://www.facebook.com"
    #  label = "Facebook"

    #[[params.footer.social]]
    #  icon = "fa-instagram"
    #  url= "https://www.instagram.com"
    #  label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/ATFutures"
      label = "GitHub"

    #[[params.footer.social]]
    #  icon = "fa-linkedin"
    #  url= "https://www.linkedin.com"
    #  label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: hugo+forty"
      url="https://themes.gohugo.io/forty/"
      alt = "forty"
